apiversion: v1
kind: Configmap
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017//frontend"    
---  
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: naveen678/frontend:1.0.0
        imagepullpolicy: Always                         # safe to pull everytime, there might be images with same version rebuilt and pushed 
        resources:
          requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "100m"

        redinessprobe:
          #httpGet:
            ##port: 8080
          tcp socket:
            port: 80 
          failureThershold: 2                            #after how many hits it should be failure
          periodseconds: 10                              #every 10sec healhth check should run
          initialDelaySeconds: 15                        #health can be ignored for first 15sec while creating
        livenessprobe:
          httpGet:
             path: /
             port: 80
          failureThershold: 2                            #after how many hits it should be failure
          periodseconds: 10                              #every 10sec healhth check should run 
---
apiversion: v1                                            #clusterip
kind: Service
metadata: 
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop                                      #labels are used as selectors
    tier: frontend
    component: frontend 
  ports: 
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port        