apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
data:
  CART_HOST: "cart"
  CART_PORT: "mongodb://mongodb:27017//payment"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment
    spec:
      containers:
        - name: payment
          image: naveen678/payment:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"

          readinessProbe:
            # httpGet:
            #   port: 8080
            tcpSocket:
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
            initialDelaySeconds: 15

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  selector:
    project: roboshop
    tier: backend
    component: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080






# apiVersion: v1
# kind: Configmap
# metadata:
#   name: payment
#   namespace: roboshop
#   labels:
#     project: roboshop
#     tier: backend
#     component: payment
# data:
#   CART_HOST: "cart"
#   CART_PORT: "mongodb://mongodb:27017//payment"
#   USER_HOST: "user"
#   USER_PORT: "8080"
#   AMQP_HOST: "rabbitmq"
#   AMQP_USER: "roboshop"
#   AMQP_PASS: "roboshop123"
# ---   
# apiVersion: apps/v1 
# kind: Deployment
# metadata:
#   name: payment
#   namespace: roboshop
#   # these labels are replicaset labels
#   labels:
#     project: roboshop
#     tier: backend
#     component: payment
# spec:
#   replicas: 1
#   selector:
#     # using these labels replica set selects the pod
#     matchLabels:
#       project: roboshop
#       tier: backend
#       component: payment
#   # This is pod definition, pod is subset of replicaset
#   template:
#     metadata:
#       labels:
#         project: roboshop
#         tier: backend
#         component: payment
#     spec:
#       containers:
#       - name: nginx
#         image: naveen678/payment:1.0.0
#         imagepullpolicy: Always                         # safe to pull everytime, there might be images with same version rebuilt and pushed 
#         resources:
#           requests:
#           memory: "128Mi"
#           cpu: "100m"
#         limits:
#           memory: "128Mi"
#           cpu: "100m"

#         redinessprobe:
#           #httpGet:
#             ##port: 8080
#           tcp socket:
#             port: 8080  
#           failureThershold: 2                            #after how many hits it should be failure
#           periodseconds: 10                              #every 10sec healhth check should run
#           initialDelaySeconds: 15                        #health can be ignored for first 15sec while creating
#         livenessprobe:
#           httpGet:
#              path: /health
#              port: 8088
#           failureThershold: 2                            #after how many hits it should be failure
#           periodseconds: 10                              #every 10sec healhth check should run 
                                                               
#         envfrom:
#          - configmapRef:
#              name: payment
# ---
# apiVersion: v1                                            #clusterip
# kind: Service
# metadata: 
#   name: payment
#   namespace: roboshop
#   labels:
#     project: roboshop
#     tier: backend
#     component: payment
# spec:
#   selector:
#     project: roboshop                                      #labels are used as selectors
#     tier: backend
#     component: payment 
#   ports: 
#   - protocol: TCP
#     port: 8080 # service port
#     targetPort: 8080 # container port        





