apiVersion: v1
kind: Configmap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"    
---  
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
      - name: nginx
        image: naveen678/shipping:1.0.0
        imagepullpolicy: Always                         # safe to pull everytime, there might be images with same version rebuilt and pushed 
        resources:
          requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "100m"

        redinessprobe:
          #httpGet:
            ##port: 8080
          tcpsocket:
            port: 8080  
          failureThershold: 2                            #after how many hits it should be failure
          periodseconds: 10                              #every 10sec healhth check should run
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 20
          periodSeconds: 10                         #health can be ignored for first 15sec while creating
        livenessprobe:
          httpGet:
             path: /health
             port: 8088
          failureThershold: 2                            #after how many hits it should be failure
          periodseconds: 10                              #every 10sec healhth check should run 
                                                               
        envfrom:
         - configmapRef:
             name: shipping
---
apiVersion: v1                                            #clusterip
kind: Service
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    project: roboshop                                      #labels are used as selectors
    tier: backend
    component: shipping 
  ports: 
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port        