apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue 
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017//catalogue"    
---  
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: nginx
        image: naveen678/catalogue:1.0.0
        imagePullPolicy: Always                         # safe to pull everytime, there might be images with same version rebuilt and pushed 
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          #httpGet:
            ##port: 8080
          tcp socket:
            port: 8080  
          failureThershold: 2                            #after how many hits it should be failure
          periodseconds: 10                              #every 10sec healhth check should run
          initialDelaySeconds: 15                        #health can be ignored for first 15sec while creating
        livenessProbe:
          httpGet:
             path: /health
             port: 8088
          failureThreshold: 2                            #after how many hits it should be failure
          periodSeconds: 10                              #every 10sec healhth check should run 
                                                               
        envFrom:
         - configMapRef:
             name: catalogue
---
apiVersion: v1                                            #clusterip
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    project: roboshop                                      #labels are used as selectors
    tier: backend
    component: catalogue 
  ports: 
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port